export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  authorName: string;
  authorRole: string;
  authorEmoji: string;
  publishedAt: Date;
  readTime: string;
  viewCount: number;
  emoji: string;
  gradient: string;
  content: BlogSection[];
  tags: string[];
  relatedSlugs: string[];
}

export interface BlogSection {
  type: "heading" | "paragraph" | "list" | "tip" | "warning" | "quote";
  text?: string;
  items?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "How to Prepare Your Dog for a Hotel Stay",
    slug: "prepare-dog-hotel-stay",
    excerpt: "Tips and tricks to make your dog's first hotel stay stress-free and enjoyable for everyone.",
    category: "Pet Care",
    authorName: "Dr. Putri Anjani",
    authorRole: "Veterinarian & Pet Behaviorist",
    authorEmoji: "👩‍⚕️",
    publishedAt: new Date("2024-03-15"),
    readTime: "5 min read",
    viewCount: 1240,
    emoji: "🏨",
    gradient: "from-amber-600 to-amber-800",
    tags: ["hotel", "dog", "tips", "first time"],
    relatedSlugs: ["healthy-pet-routine", "introduce-new-pet"],
    content: [
      { type: "paragraph", text: "Membawa anjing ke hotel untuk pertama kali bisa menjadi pengalaman yang menegangkan, baik bagi kamu maupun si anjing. Namun dengan persiapan yang tepat, pengalaman ini bisa menjadi sangat menyenangkan!" },
      { type: "heading", text: "1. Kunjungi Hotel Lebih Dulu" },
      { type: "paragraph", text: "Sebelum hari check-in, ajak anjingmu mengunjungi hotel terlebih dahulu untuk berkenalan dengan lingkungan, bau, dan staf. Ini membantu anjingmu merasa lebih familiar dan mengurangi stres saat hari-H." },
      { type: "heading", text: "2. Bawa Benda-Benda Favorit" },
      { type: "paragraph", text: "Selimut, mainan kesayangan, atau baju dengan bau kamu akan sangat membantu anjingmu merasa aman di lingkungan baru. Bau yang familiar adalah comfort terbesar bagi anjing." },
      { type: "list", items: [
        "Selimut atau bantal favoritnya",
        "Mainan kesayangan (1–2 buah, jangan terlalu banyak)",
        "Mangkuk makan/minum milik sendiri jika anjingmu pemilih",
        "Makanan yang biasa dimakan sehari-hari",
        "Obat-obatan rutin jika ada",
      ]},
      { type: "heading", text: "3. Pertahankan Rutinitas Makan" },
      { type: "paragraph", text: "Informasikan kepada staf hotel tentang jadwal makan anjingmu — jam berapa biasa makan, berapa porsinya, dan makanan apa yang diberikan. Perubahan jadwal makan bisa memicu stres dan masalah pencernaan." },
      { type: "tip", text: "💡 Pro Tip: Bawa makanan yang sama persis yang biasa dimakan anjingmu di rumah. Jangan ganti makanan saat anjing sedang adaptasi di tempat baru — bisa menyebabkan sakit perut." },
      { type: "heading", text: "4. Update Vaksinasi Sebelum Check-In" },
      { type: "paragraph", text: "Pastikan semua vaksin anjingmu sudah up-to-date sebelum menginap. Hotel terpercaya akan meminta bukti vaksinasi untuk melindungi semua hewan yang menginap. Vaksin penting antara lain Rabies, Distemper, dan Parvovirus." },
      { type: "heading", text: "5. Lakukan Trial Stay Pendek Dulu" },
      { type: "paragraph", text: "Untuk anjing yang belum pernah menginap, coba dulu durasi pendek (1–2 malam) sebelum pergi ke perjalanan panjang. Ini membantu anjingmu beradaptasi secara bertahap." },
      { type: "warning", text: "⚠️ Perhatikan: Jika anjingmu menunjukkan tanda-tanda kecemasan berlebihan (menggigit kandang, tidak mau makan 24+ jam, vokalisasi terus-menerus), konsultasikan ke dokter hewan sebelum rencana menginap." },
      { type: "heading", text: "6. Berikan Informasi Lengkap ke Staf" },
      { type: "paragraph", text: "Semakin banyak informasi yang kamu berikan kepada staf hotel, semakin baik perawatan yang akan diterima anjingmu. Jangan ragu untuk mendetailkan kebiasaan, ketakutan, dan kesenangan anjingmu." },
      { type: "list", items: [
        "Makanan/bau yang tidak disukai atau memicu reaksi alergi",
        "Apakah anjing ramah dengan anjing lain",
        "Kebiasaan tidur (suka di lantai, kasur, atau kandang)",
        "Aktivitas favorit dan yang tidak disukai",
        "Kontak darurat selain nomor utama",
      ]},
      { type: "quote", text: "\"Persiapan adalah kunci. Anjing yang datang ke hotel dengan pemilik yang rileks dan percaya akan jauh lebih mudah beradaptasi dibanding anjing yang pemiliknya cemas.\" — Dr. Putri Anjani" },
    ],
  },
  {
    id: "2",
    title: "5 Signs Your Cat Needs Professional Grooming",
    slug: "cat-needs-grooming",
    excerpt: "Regular grooming is essential for your cat's health. Learn to spot the signs that it's time to visit a professional groomer.",
    category: "Pet Health",
    authorName: "Grooming Expert Team",
    authorRole: "Certified Master Groomers",
    authorEmoji: "✂️",
    publishedAt: new Date("2024-03-10"),
    readTime: "4 min read",
    viewCount: 876,
    emoji: "🐱",
    gradient: "from-pink-400 to-rose-500",
    tags: ["cat", "grooming", "health", "tips"],
    relatedSlugs: ["healthy-pet-routine", "prepare-dog-hotel-stay"],
    content: [
      { type: "paragraph", text: "Kucing memang dikenal sebagai hewan yang bersih dan pandai merawat dirinya sendiri. Namun ada kondisi-kondisi tertentu di mana bantuan groomer profesional sangat dibutuhkan. Kenali tanda-tandanya sebelum terlambat!" },
      { type: "heading", text: "1. Bulu Kusut dan Menggumpal (Matting)" },
      { type: "paragraph", text: "Bulu yang kusut dan membentuk gumpalan (mat) adalah tanda paling jelas bahwa kucingmu butuh bantuan groomer. Matting yang dibiarkan bisa menyebabkan iritasi kulit, infeksi, bahkan rasa sakit karena menarik kulit saat bergerak." },
      { type: "warning", text: "⚠️ Jangan coba memotong mat sendiri dengan gunting biasa! Sangat berbahaya karena kulit kucing sangat tipis dan mudah terluka. Percayakan pada groomer profesional yang menggunakan alat khusus." },
      { type: "heading", text: "2. Bulu Berlebih dan Kerontokan Tinggi" },
      { type: "paragraph", text: "Saat musim ganti bulu (shedding season), kucing ras panjang bisa kehilangan sangat banyak bulu. Professional de-shedding treatment bisa mengurangi kerontokan hingga 80% dan mencegah pembentukan hairball yang berbahaya." },
      { type: "heading", text: "3. Bau Badan Tidak Normal" },
      { type: "paragraph", text: "Kucing yang sehat biasanya tidak berbau. Jika kucingmu mulai berbau tidak sedap, ini bisa menandakan masalah kulit, infeksi telinga, atau masalah kesehatan lain yang perlu segera ditangani." },
      { type: "tip", text: "💡 Groomer profesional juga memeriksa kondisi telinga, kulit, dan kuku saat sesi grooming. Mereka sering kali mendeteksi masalah kesehatan awal sebelum menjadi serius." },
      { type: "heading", text: "4. Kuku Terlalu Panjang" },
      { type: "paragraph", text: "Kuku yang terlalu panjang bisa melengkung dan menembus bantalan kaki kucing, menyebabkan rasa sakit dan infeksi. Tanda-tandanya: kucing terdengar 'klak-klak' saat berjalan di lantai keras, atau sering tersangkut di karpet." },
      { type: "heading", text: "5. Kucing Menolak Digrooming Sendiri" },
      { type: "paragraph", text: "Kucing yang menghentikan kebiasaan grooming diri sendiri bisa mengalami rasa sakit (arthritis, cedera), obesitas yang membuat tidak bisa menjangkau area tertentu, atau masalah kesehatan lain. Ini adalah sinyal untuk segera ke dokter hewan dan groomer." },
      { type: "list", items: [
        "Frekuensi ideal grooming kucing berbulu panjang: setiap 4–6 minggu",
        "Kucing berbulu pendek: setiap 8–12 minggu",
        "Kuku dipotong setiap 2–3 minggu",
        "Telinga dibersihkan setiap bulan",
        "Gigi disikat 2–3 kali seminggu",
      ]},
      { type: "quote", text: "\"Grooming bukan sekadar soal penampilan — ini adalah bagian penting dari perawatan kesehatan kucing yang sering diabaikan.\" — Tim Groomer Central Pet" },
    ],
  },
  {
    id: "3",
    title: "The Best Diet for Senior Dogs (7+ Years)",
    slug: "diet-senior-dogs",
    excerpt: "As dogs age, their nutritional needs change significantly. Here's a complete guide to feeding your senior dog for optimal health.",
    category: "Nutrition",
    authorName: "Dr. Ahmad Fauzan",
    authorRole: "Veterinary Nutritionist",
    authorEmoji: "👨‍⚕️",
    publishedAt: new Date("2024-03-05"),
    readTime: "7 min read",
    viewCount: 2150,
    emoji: "🦴",
    gradient: "from-amber-400 to-orange-500",
    tags: ["dog", "nutrition", "senior", "diet", "health"],
    relatedSlugs: ["healthy-pet-routine", "essential-vaccines-pets"],
    content: [
      { type: "paragraph", text: "Anjing senior (7 tahun ke atas, atau lebih awal untuk ras besar) mengalami perubahan metabolisme, penurunan massa otot, dan rentan terhadap berbagai penyakit. Diet yang tepat bisa membuat perbedaan besar dalam kualitas hidup dan umur panjang mereka." },
      { type: "heading", text: "Perubahan Fisiologis yang Terjadi" },
      { type: "list", items: [
        "Metabolisme melambat → mudah gemuk jika porsi tidak disesuaikan",
        "Massa otot berkurang → butuh protein berkualitas tinggi",
        "Pencernaan kurang efisien → butuh makanan yang mudah dicerna",
        "Fungsi ginjal menurun → perlu pembatasan fosfor",
        "Sendi mulai kaku → butuh suplemen glucosamine & omega-3",
        "Imunitas menurun → perlu antioksidan lebih banyak",
      ]},
      { type: "heading", text: "Nutrisi Utama yang Dibutuhkan Anjing Senior" },
      { type: "heading", text: "🥩 Protein — Kunci Utama" },
      { type: "paragraph", text: "Berlawanan dengan mitos lama, anjing senior justru membutuhkan protein yang LEBIH BANYAK, bukan lebih sedikit (kecuali ada masalah ginjal yang dikonfirmasi dokter hewan). Protein berkualitas tinggi membantu mempertahankan massa otot yang cenderung turun seiring usia." },
      { type: "tip", text: "💡 Cari makanan dengan protein hewani (ayam, ikan, daging sapi) sebagai bahan pertama dalam daftar ingredients. Hindari produk dengan 'meat by-products' atau 'meal' sebagai sumber utama." },
      { type: "heading", text: "🐟 Omega-3 — Anti-Inflamasi Alami" },
      { type: "paragraph", text: "Asam lemak omega-3 (EPA dan DHA) sangat penting untuk anjing senior karena membantu mengurangi peradangan sendi, menjaga kesehatan otak, dan meningkatkan kualitas bulu. Sumber terbaik: minyak ikan salmon atau suplemen fish oil." },
      { type: "heading", text: "🦷 Kalsium & Fosfor — Perlu Keseimbangan" },
      { type: "paragraph", text: "Rasio kalsium:fosfor yang tepat (sekitar 1.2:1) sangat penting. Terlalu banyak fosfor bisa membebani ginjal yang sudah mulai menurun fungsinya. Pilih makanan yang diformulasikan khusus untuk anjing senior." },
      { type: "heading", text: "Makanan yang Direkomendasikan" },
      { type: "list", items: [
        "Makanan kering (kibble) khusus senior dengan ukuran kibble lebih kecil",
        "Makanan basah untuk anjing dengan gigi sensitif atau nafsu makan menurun",
        "Ikan salmon atau tuna kukus sebagai topping (2-3x seminggu)",
        "Wortel dan brokoli kukus sebagai camilan sehat",
        "Suplemen glucosamine untuk kesehatan sendi",
      ]},
      { type: "heading", text: "Makanan yang Harus Dihindari" },
      { type: "list", items: [
        "Makanan tinggi sodium (merusak ginjal)",
        "Camilan manis atau bertepung berlebihan",
        "Tulang keras yang bisa melukai gigi yang sudah rapuh",
        "Makanan berbumbu bawang putih/bawang merah (toksik untuk anjing)",
        "Makanan berlemak tinggi (risiko pankreatitis meningkat pada anjing tua)",
      ]},
      { type: "warning", text: "⚠️ Penting: Sebelum mengubah diet anjing seniormu, konsultasikan dulu dengan dokter hewan. Terutama jika anjingmu memiliki kondisi kesehatan seperti diabetes, penyakit ginjal, atau masalah jantung." },
      { type: "heading", text: "Jadwal Makan Ideal" },
      { type: "paragraph", text: "Anjing senior lebih baik diberi makan 2–3 kali sehari dalam porsi yang lebih kecil, dibanding 1–2 kali sehari. Ini membantu pencernaan yang sudah tidak seefisien dulu dan mencegah masalah kembung (bloat)." },
      { type: "quote", text: "\"Investasi terbaik untuk anjing seniormu adalah makanan berkualitas dan pemeriksaan rutin ke dokter hewan setiap 6 bulan. Usia boleh bertambah, tapi kualitas hidup tidak harus menurun.\" — Dr. Ahmad Fauzan" },
    ],
  },
  {
    id: "4",
    title: "How to Introduce a New Pet to Your Home",
    slug: "introduce-new-pet",
    excerpt: "Making the transition smooth for both your existing and new pets requires patience and the right strategy.",
    category: "Training",
    authorName: "Pet Behavior Specialist",
    authorRole: "Certified Animal Behaviorist",
    authorEmoji: "🧠",
    publishedAt: new Date("2024-02-28"),
    readTime: "6 min read",
    viewCount: 934,
    emoji: "🐾",
    gradient: "from-emerald-400 to-teal-500",
    tags: ["training", "behavior", "new pet", "multi-pet"],
    relatedSlugs: ["healthy-pet-routine", "prepare-dog-hotel-stay"],
    content: [
      { type: "paragraph", text: "Memperkenalkan hewan peliharaan baru ke rumah yang sudah ada hewan lain adalah proses yang butuh kesabaran dan strategi yang tepat. Terburu-buru bisa mengakibatkan konflik yang mempengaruhi kesehatan mental semua hewan di rumah." },
      { type: "heading", text: "Sebelum Hewan Baru Datang" },
      { type: "list", items: [
        "Siapkan ruang terpisah untuk hewan baru (kamar, ruang tamu kecil, atau kandang besar)",
        "Beli perlengkapan baru — jangan berbagi mangkuk, tempat tidur, atau mainan dulu",
        "Pastikan hewan baru sudah divaksin dan diperiksa dokter hewan",
        "Persiapkan hewan lama dengan melatih perintah dasar 'leave it' dan 'stay'",
      ]},
      { type: "heading", text: "Fase 1: Pengenalan Bau (Hari 1–7)" },
      { type: "paragraph", text: "Sebelum bertemu langsung, kenalkan bau masing-masing hewan terlebih dahulu. Tukar selimut atau handuk yang sudah digunakan. Letakkan barang dengan bau hewan baru di area yang sering dilalui hewan lama, dan sebaliknya." },
      { type: "tip", text: "💡 Teknik 'scent swapping' ini sangat efektif terutama untuk kucing, yang sangat territory-driven. Jangan skip fase ini meskipun kamu ingin cepat mempertemukan mereka." },
      { type: "heading", text: "Fase 2: Kontak Visual Tanpa Sentuhan (Hari 3–10)" },
      { type: "paragraph", text: "Buka sedikit pintu ruang hewan baru agar mereka bisa saling melihat dan mencium bau, tapi tidak bisa langsung kontak fisik. Bisa juga gunakan baby gate. Amati reaksi keduanya — hewan yang terlihat santai atau penasaran adalah tanda bagus." },
      { type: "heading", text: "Fase 3: Pertemuan Pertama yang Diawasi" },
      { type: "paragraph", text: "Saat keduanya sudah terlihat tenang melihat satu sama lain melalui penghalang, coba pertemukan di area netral (bukan ruang pribadi salah satu hewan). Jaga durasi singkat (5–10 menit) dan awasi terus." },
      { type: "warning", text: "⚠️ Tanda-tanda yang harus diwaspadai: memburu, mengejar dengan agresif, menggeram terus-menerus, atau bulu berdiri. Jika ini terjadi, pisahkan dan mundur ke fase sebelumnya selama beberapa hari lagi." },
      { type: "heading", text: "Tips Khusus: Anjing + Kucing" },
      { type: "list", items: [
        "Selalu kenalkan anjing dalam kondisi talinya terpasang dulu",
        "Pastikan kucing punya jalur pelarian yang mudah (kursi tinggi, rak, dll)",
        "Jangan pernah paksa kucing 'berteman' dengan membawanya mendekat ke anjing",
        "Beri makan di tempat terpisah untuk menghindari kompetisi",
        "Berikan perhatian ekstra pada hewan yang sudah ada lebih dulu",
      ]},
      { type: "heading", text: "Berapa Lama Proses Ini?" },
      { type: "paragraph", text: "Setiap hewan berbeda. Beberapa bisa akur dalam hitungan minggu, yang lain butuh 3–6 bulan. Jangan terburu-buru dan jangan menyerah. Konsistensi dan kesabaran adalah kunci utama." },
      { type: "quote", text: "\"Tidak ada hewan yang 'susah diatur' — hanya ada proses pengenalan yang terlalu terburu-buru. Berikan waktu yang cukup dan hasilnya akan selalu lebih baik.\"" },
    ],
  },
  {
    id: "5",
    title: "Essential Vaccines Every Pet Owner Should Know About",
    slug: "essential-vaccines-pets",
    excerpt: "A comprehensive guide to vaccination schedules for dogs and cats — what's needed, when, and why it matters.",
    category: "Pet Health",
    authorName: "Dr. Siti Rahayu",
    authorRole: "Veterinarian, Spesialis Penyakit Infeksius",
    authorEmoji: "💉",
    publishedAt: new Date("2024-02-20"),
    readTime: "8 min read",
    viewCount: 3420,
    emoji: "🛡️",
    gradient: "from-blue-400 to-cyan-500",
    tags: ["vaccine", "health", "dog", "cat", "prevention"],
    relatedSlugs: ["diet-senior-dogs", "healthy-pet-routine"],
    content: [
      { type: "paragraph", text: "Vaksinasi adalah salah satu investasi terpenting yang bisa kamu lakukan untuk kesehatan hewan peliharaanmu. Penyakit-penyakit yang bisa dicegah dengan vaksin seringkali fatal dan sangat mahal jika sampai menginfeksi." },
      { type: "heading", text: "Vaksin Wajib untuk Anjing" },
      { type: "heading", text: "🦠 Rabies" },
      { type: "paragraph", text: "Vaksin paling penting — wajib secara hukum di banyak daerah. Rabies adalah penyakit fatal yang bisa menular ke manusia. Jadwal: puppy 3–4 bulan, booster 1 tahun kemudian, lalu setiap 1–3 tahun tergantung jenis vaksin." },
      { type: "heading", text: "🦠 DHPP (Distemper, Hepatitis, Parvovirus, Parainfluenza)" },
      { type: "paragraph", text: "Ini adalah vaksin 'core' atau vaksin dasar yang wajib dimiliki semua anjing tanpa terkecuali. Parvovirus terutama sangat berbahaya untuk puppy dan bisa membunuh dalam hitungan hari." },
      { type: "list", items: [
        "Puppy 6–8 minggu: dosis pertama DHPP",
        "Puppy 10–12 minggu: booster DHPP kedua",
        "Puppy 14–16 minggu: booster DHPP ketiga",
        "1 tahun kemudian: booster",
        "Dewasa: setiap 3 tahun sekali",
      ]},
      { type: "heading", text: "Vaksin Wajib untuk Kucing" },
      { type: "heading", text: "🦠 FVRCP (Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia)" },
      { type: "paragraph", text: "Vaksin core untuk semua kucing. Melindungi dari flu kucing dan panleukopenia (distemper kucing) yang sangat menular dan sering fatal pada anak kucing." },
      { type: "heading", text: "🦠 Rabies (untuk Kucing)" },
      { type: "paragraph", text: "Sama pentingnya dengan untuk anjing. Kucing yang dibiarkan keluar rumah WAJIB divaksin rabies. Bahkan kucing indoor pun direkomendasikan karena kecelakaan bisa terjadi." },
      { type: "tip", text: "💡 Gunakan fitur Health Passport di Central Pet untuk menyimpan semua riwayat vaksin dan mendapatkan reminder otomatis sebelum jadwal vaksin jatuh tempo. Gratis untuk semua pengguna!" },
      { type: "heading", text: "Vaksin Opsional (Berdasarkan Gaya Hidup)" },
      { type: "list", items: [
        "Bordetella (Kennel Cough) — wajib jika anjing sering ke hotel atau daycare",
        "Leptospirosis — untuk anjing yang sering ke area outdoor/sungai",
        "Lyme Disease — untuk daerah dengan banyak kutu",
        "FeLV (Feline Leukemia) — untuk kucing yang keluar rumah",
        "FIV — kucing berisiko tinggi terekspos kucing liar",
      ]},
      { type: "heading", text: "Apa yang Terjadi Setelah Vaksin?" },
      { type: "paragraph", text: "Reaksi ringan seperti lesu, nafsu makan berkurang, atau sedikit bengkak di area suntikan adalah normal dan biasanya hilang dalam 1–2 hari. Hubungi dokter hewan segera jika ada reaksi parah seperti pembengkakan wajah, muntah, atau kesulitan bernapas." },
      { type: "warning", text: "⚠️ Penting: Jangan vaksin hewan yang sedang sakit atau dalam kondisi stres. Tunggu hingga kondisinya pulih untuk memastikan vaksin bekerja optimal dan mengurangi risiko efek samping." },
      { type: "quote", text: "\"Mencegah selalu jauh lebih murah dan lebih mudah daripada mengobati. Satu kali vaksin bisa melindungi hewan peliharaanmu dari penyakit yang bisa menghabiskan jutaan rupiah untuk diobati.\" — Dr. Siti Rahayu" },
    ],
  },
  {
    id: "6",
    title: "Building a Healthy Routine for Your Pet",
    slug: "healthy-pet-routine",
    excerpt: "Exercise, diet, play, and rest — how to balance it all for a happy, healthy, and well-adjusted pet.",
    category: "Pet Care",
    authorName: "Central Pet Team",
    authorRole: "Pet Care Specialists",
    authorEmoji: "🌟",
    publishedAt: new Date("2024-02-15"),
    readTime: "5 min read",
    viewCount: 1580,
    emoji: "🌈",
    gradient: "from-amber-600 to-amber-800",
    tags: ["routine", "health", "lifestyle", "exercise", "diet"],
    relatedSlugs: ["diet-senior-dogs", "essential-vaccines-pets"],
    content: [
      { type: "paragraph", text: "Hewan peliharaan yang sehat dan bahagia bukan kebetulan — mereka adalah hasil dari rutinitas yang konsisten dan penuh kasih sayang. Sama seperti manusia, pola hidup yang teratur memberikan dampak luar biasa pada kesehatan fisik dan mental hewan peliharaanmu." },
      { type: "heading", text: "Rutinitas Harian yang Ideal" },
      { type: "heading", text: "🌅 Pagi (06.00–09.00)" },
      { type: "list", items: [
        "Makan pagi — selalu di jam yang sama setiap hari",
        "Jalan pagi untuk anjing (minimal 20–30 menit)",
        "Waktu bermain ringan untuk kucing",
        "Cek kondisi tubuh: mata, hidung, bulu, nafsu makan",
      ]},
      { type: "heading", text: "☀️ Siang (12.00–14.00)" },
      { type: "list", items: [
        "Makan siang (jika jadwal makan 3x sehari)",
        "Waktu istirahat dan tidur — sangat penting untuk kucing",
        "Isi ulang air minum yang segar",
        "Sesi singkat enrichment (puzzle feeder, mainan baru)",
      ]},
      { type: "heading", text: "🌆 Sore–Malam (17.00–21.00)" },
      { type: "list", items: [
        "Makan malam — waktu terbesar untuk berinteraksi",
        "Waktu bermain aktif dan bonding",
        "Grooming ringan: sisir bulu, cek kuku",
        "Jalan sore untuk anjing (jika memungkinkan)",
        "Wind-down time: tenang, kurangi stimulasi",
      ]},
      { type: "tip", text: "💡 Konsistensi adalah kunci. Anjing dan kucing adalah makhluk kebiasaan. Perubahan jadwal yang tiba-tiba bisa menyebabkan stres dan masalah perilaku. Gunakan reminder di hp untuk membantu menjaga konsistensi." },
      { type: "heading", text: "Kebutuhan Olahraga per Jenis Hewan" },
      { type: "list", items: [
        "Anjing kecil (Chihuahua, Pom): 20–30 menit/hari",
        "Anjing sedang (Beagle, Corgi): 45–60 menit/hari",
        "Anjing besar (Labrador, Husky): 60–90 menit/hari",
        "Kucing indoor: 2x15 menit sesi bermain aktif/hari",
        "Kucing senior: disesuaikan dengan kondisi fisik",
      ]},
      { type: "heading", text: "Pentingnya Mental Stimulation" },
      { type: "paragraph", text: "Olahraga fisik saja tidak cukup. Hewan peliharaan — terutama ras cerdas — juga butuh stimulasi mental untuk mencegah kebosanan yang bisa berujung pada perilaku destruktif seperti menggigit furnitur atau excessive barking." },
      { type: "list", items: [
        "Puzzle feeder: taruh makanan dalam mainan puzzle",
        "Hide and seek dengan camilan",
        "Training sesi singkat (5–10 menit, 2x sehari)",
        "Rotasi mainan setiap beberapa hari",
        "Window perch untuk kucing (birdwatching alami)",
      ]},
      { type: "heading", text: "Tanda Rutinitas Kamu Berhasil" },
      { type: "list", items: [
        "Nafsu makan stabil dan antusias saat jam makan",
        "Tidur dengan nyenyak di waktu yang konsisten",
        "Aktif dan playful di waktu yang tepat",
        "Jarang sakit atau membutuhkan kunjungan dokter darurat",
        "Berat badan stabil dan ideal",
      ]},
      { type: "quote", text: "\"Rutinitas yang baik adalah hadiah terbesar yang bisa kamu berikan pada hewan peliharaanmu. Mereka tidak bisa meminta, tapi mereka selalu memberikan yang terbaik ketika kebutuhannya terpenuhi.\" — Central Pet Team" },
    ],
  },
];

export function getBlogBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string): BlogPost[] {
  const post = getBlogBySlug(slug);
  if (!post) return [];
  return post.relatedSlugs
    .map((s) => getBlogBySlug(s))
    .filter((p): p is BlogPost => p !== undefined);
}
